name: GitHub Pages deploy
on:
  push:
    branches:
      - master
jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 12.13.0
    - name: NPM or Yarn install with caching
      uses: bahmutov/npm-install@v1.1.0
    - uses: borales/actions-yarn@v2.1.0
      with:
        cmd: build # will run `yarn build` command
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@2.0.0
      env:
        EMAIL: hughfenghen@gmail.com               # must be a verified email
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }} # https://github.com/settings/tokens
        BUILD_DIR: dist/                     # "_site/" by defaul
